language: ruby

rvm:
  - 2.6.1

env:
  global:
    - RAILS_ENV=test

before_install:
  - gem install bundler

before_script:
  - gem install bundle-audit

script:
  - RAILS_ENV=test bundle exec rake db:setup
  - bundle exec rspec
  - bundle exec rubocop --config .rubocop.yml
  - bundle-audit check --update
